version: 2
jobs:
  generate:
    working_directory: ~/workspace
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys: - v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn package cache
          paths:
            - ~/.cache/yarn
          keys: - v1-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn run lint
      - run: yarn run generate
      - persist_to_workspace:
          root: '.'
          paths:
            - dist
  deploy:
    working_directory: ~/workspace
    docker:
      - image: node:10.15.3
    steps:
      - attach_workspace:
          at: '.'
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -ahv --delete ./dist/* ${DEPLOY_DEST}
workflows:
  version: 2
  deploy:
    jobs:
      - generate
      - deploy:
          requires:
            - generate
          filters:
            branches:
              only: master